#! /bin/bash

# assign classes to hosts

case $HOSTNAME in
	ubuntu)
		echo "FAIBASE DHCPC UBUNTU UBUNTU_1204_X86" ;;
	*)
		echo "FAIBASE DHCPC UBUNTU" ;;
esac

#ubuntu and debian should both use grub
ifclass -o I386 AMD64 && echo GRUB_PC
exit 0
