#! /bin/bash

# assign classes to hosts

#BASE: Class needed for a base installation
#DHCPC: Class to configure network interface for dhcp
#UBUNTU: Class for Ubuntu installations

#UBUNTU_SERVER_1204_X86: Uses Ubuntu Server 12.04 x86 for base.tgz file

case $HOSTNAME in
	ubuntu)
		echo "BASE DHCPC UBUNTU UBUNTU_SERVER_1204_X86" ;;
	*)
		echo "BASE DHCPC UBUNTU UBUNTU_SERVER_1204_X86" ;;
esac

#ubuntu and debian should both use grub
ifclass -o I386 AMD64 && echo GRUB_PC
exit 0
